# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates/qt/video_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.group_video = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_video.sizePolicy().hasHeightForWidth())
        self.group_video.setSizePolicy(sizePolicy)
        self.group_video.setObjectName("group_video")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_video)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_video_vertical_layout = QtWidgets.QVBoxLayout()
        self.group_video_vertical_layout.setSpacing(6)
        self.group_video_vertical_layout.setObjectName("group_video_vertical_layout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.group_video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_play = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_2.addWidget(self.btn_play)
        self.btn_stop = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        self.group_video_vertical_layout.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.group_video_vertical_layout)
        self.horizontalLayout.addWidget(self.group_video)
        self.group_box_controls = QtWidgets.QGroupBox(Form)
        self.group_box_controls.setObjectName("group_box_controls")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_box_controls)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnUp = QtWidgets.QPushButton(self.group_box_controls)
        self.btnUp.setObjectName("btnUp")
        self.verticalLayout_3.addWidget(self.btnUp)
        self.widget = QtWidgets.QWidget(self.group_box_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLeft = QtWidgets.QPushButton(self.widget)
        self.btnLeft.setObjectName("btnLeft")
        self.horizontalLayout_3.addWidget(self.btnLeft)
        self.btnRight = QtWidgets.QPushButton(self.widget)
        self.btnRight.setObjectName("btnRight")
        self.horizontalLayout_3.addWidget(self.btnRight)
        self.verticalLayout_3.addWidget(self.widget)
        self.btnDown = QtWidgets.QPushButton(self.group_box_controls)
        self.btnDown.setObjectName("btnDown")
        self.verticalLayout_3.addWidget(self.btnDown)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.group_box_controls)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.group_video.setTitle(_translate("Form", "Live Video"))
        self.groupBox_3.setTitle(_translate("Form", "Video playback controls"))
        self.btn_play.setText(_translate("Form", "Play"))
        self.btn_stop.setText(_translate("Form", "Stop"))
        self.group_box_controls.setTitle(_translate("Form", "Controls"))
        self.btnUp.setText(_translate("Form", "Up"))
        self.btnLeft.setText(_translate("Form", "<"))
        self.btnRight.setText(_translate("Form", ">"))
        self.btnDown.setText(_translate("Form", "Down"))
